agent:
  defer: false
  defertime: 180
  highdelay: 599
  kill: false
  lowdelay: 69
  recordpulse: True
drivers:
  mssql: MSSQL-17
  mysql: native
eaedb:
  connection: postgresql
  db: reportingdb
  passwd: eaeuser
  port: 5432
  schema: staging
  server: kon_db
  user: eaeuser
housekeeping:
  framework:
    agentpulse: 16
    api_salesforce_tracker: 180
    api_traces: 90
    cachetraces: 31
    chunktraces: 31
    collectiontracker: 180
    errorlogs: 366
    tabshapetraces: 15
    tracker: 180
log_directory: dimLogs
migrations: ../../../../database/reporting_db
pandas:
  bigset: 500000
  parallelism: true
  tinyset: 75000
salesforce:
  cid: 3MVG9PE4xB9wtoY8w4VZoDIfOOua2XA_iJw9cGi270bVwJAJ6S4iZ5mcpffviN.GJ_Fx0.UF_eimRFRVmRxeL
  data_ctype: application/json
  dateformat: m/d/Y
  days_frequency: 31
  pwd: Passion@3owcF8Vw8VpqodZY7v9boU3Ph
  secrect: 1F35E6ED29FB35F484B562F02236479E92F16B71BE5A5B1CED787AD42EBB7D2D
  start_date: 2016-01-01
  token: https://cs70.salesforce.com/services/oauth2/token
  token_ctype: application/x-www-form-urlencoded
  uid: divs@kcloudtechnologies.com.elearning
smtp:
  enable: false
  from: EAE Data Integration <statzen@eae.inspireme.com>
  server: 172.16.3.129
