datastore:
  connection: postgresql
  port: 5432
  server: zipdb
  user: pgusr
  passwd: pgusr
  db: zipdb

migrations: ../database/reporting_db
max_workers: 3

xport_cfg:
  fmt_extension: json
  dat_extension: txt
  field_separator: '|'
  worker_xtn: io
  zip_path: worker/data/
  archive_path: worker/archive/
  dat_quote: '`'
