eaedb:
  connection: postgresql
  port: 5432
  server: 172.17.0.1
  user: eaeuser
  passwd: eaeuser
  db: reportingdb
  schema: staging
  cache_schema: cached
  purge_schema: purged

migrations: ../database/reporting_db
max_workers: 3

agent:
  snooze_time: 9
  latency: 369
  sfdc_latency: 999
  pid_files: /app/eaedim/dimlogs/
  full_dv_min_hour: 1
  full_dv_max_hour: 5
  skip_build_cache: true

salesforce:
  token: https://cs70.salesforce.com/services/oauth2/token
  token_ctype: application/x-www-form-urlencoded
  data_ctype: application/json
  cid: 3MVG9PE4xB9wtoY8w4VZoDIfOOua2XA_iJw9cGi270bVwJAJ6S4iZ5mcpffviN.GJ_Fx0.UF_eimRFRVmRxeL
  pwd: Passion@3owcF8Vw8VpqodZY7v9boU3Ph
  secrect: 1F35E6ED29FB35F484B562F02236479E92F16B71BE5A5B1CED787AD42EBB7D2D
  uid: divs@kcloudtechnologies.com.elearning
  dateformat: m/d/Y
  start_date: 1/1/2016
  days_frequency: 15

dv_load:
  drop_staging: true
  recreate_index: false
  enforce_integrity: true
  record_stage_count: true

xport_cfg:
  fmt_extension: json
  dat_extension: txt
  field_separator: '|'
  worker_xtn: io
  en_zip_path: worker/_io/
  en_key_passcode: SFASFASFA
  archive_path: worker/archive/
  dat_quote: '`'
  key_file: worker/_io/24DCCFCAA2DC0B2FB7BB35DBB1A768A71FAC7066.asc
  record_rowversion: true
  ingest_pki: true
