version: "3.6"

networks: 
    zipnet:
        name: concurrentzipset

volumes:
    eae_dat:
        external: false
        name: vol_zipset_dat

services:
    zipdb:
        image: postgres:12.1
        container_name: zipdb
        hostname: pgxdb
        restart: always
        ports:
            - 56003:5432
        networks: 
            - zipnet
        environment:
            POSTGRES_USER: pgusr
            POSTGRES_DB: zipdb
            POSTGRES_PASSWORD: pgusr
        volumes:
            - eae_dat:/var/lib/postgresql/data
        logging:
            driver: none

    ezetl:
        build: .
        command: python waker.py 696969
        container_name: ezetl
        hostname: ezetl
        image: concurrent-zip-etl
        working_dir: /app
        volumes:
            - /home/raghu.neerukonda/journals/concurrent-zip-etl:/app
        networks: 
            - zipnet
        depends_on:
            - zipdb
