eaedb:
  port: 5432
  host: 10.200.0.235
  uid: reportingdbuser
  pwd: reportingdbuser
  db: reportingdb
  schema: staging

migrations: /dim/migrations
log_directory: dimLogs

pandas:
  tinyset: 75000
  bigset: 500000
  parallelism: True

drivers:
  mssql: MSSQL-17
  mysql: native

agent:
  lowdelay: 59
  highdelay: 599
  defer: False
  kill: False

smtp:
  server: 172.16.3.129
  from: EAE Data Integration <statzen@eae.inspireme.com>
  enable: true

salesforce:
  token: https://cs70.salesforce.com/services/oauth2/token
  data: https://cs70.salesforce.com/services/apexrest/getClosedWonOpportunities
  token_ctype: application/x-www-form-urlencoded
  data_ctype: application/json
  cid: 3MVG9PE4xB9wtoY8w4VZoDIfOOua2XA_iJw9cGi270bVwJAJ6S4iZ5mcpffviN.GJ_Fx0.UF_eimRFRVmRxeL
  pwd: Passion@3owcF8Vw8VpqodZY7v9boU3Ph
  csecrect: 1F35E6ED29FB35F484B562F02236479E92F16B71BE5A5B1CED787AD42EBB7D2D
  uid: 3MVG9PE4xB9wtoY8w4VZoDIfOOua2XA_iJw9cGi270bVwJAJ6S4iZ5mcpffviN.GJ_Fx0.UF_eimRFRVmRxeL
  dateformat: %m/%d/%Y
