eaedb:
  port: 5432
  host: 10.200.0.235
  uid: reportingdbuser
  pwd: reportingdbuser
  db: reportingdb
  schema: staging

migrations: /dim/migrations
log_directory: dimLogs

pandas:
  tinyset: 75000
  bigset: 500000
  parallelism: True

drivers:
  mssql: MSSQL-17
  mysql: native

agent:
  lowdelay: 59
  highdelay: 599
  defer: False
  kill: False

smtp:
  server: 172.16.3.129
  from: EAE Data Integration <eae@inspireme.com>
  enable: true
