eaedb:
    host: 172.16.1.179
    port: 14217
    user: eaeadmin
    pass_key: PyyXXmZBFBpeT0vjIjpVR-x6xxFfITrz8y44hNFc7Gc=
    passwd: gAAAAABaL40XPnrmp24GRlHYdZhP5-jcey3Zii8l63TXQeo1uVE1oDeB5TyWKJdFnvYBe-hvi48kkYpEV_Z2-LmlpT18PE7QBA==
    db: eae
    authentication: False

backup:
    disabled: False
    deferred: False
    debug: True
    path: /eae/bkp/
    retention: 36                         # NUMBER OF RETENTION SET ON DISK
    frequency: [1,14,19]
    day_of_week: [0,1,2,3,4,5,6]          # 5-SAT, 6-SUN

index:
    disabled: False
    deferred: False
    debug: True
    enabled: True
    stats: True
    day_of_week: [0,1,2,3,4,5,6]

log_retention:
    logDTSAdminActions: 60
    logDTSActions: 60
    logForkerActions: 60
    logDTSErrors: 100

other:
    sendemail: no
