eaedb:
  port: 5432
  server: 172.17.0.6
  user: postgres
  passwd: reporter
  db: reportingdb
  schema: staging

migrations: ../../../../database/reporting_db
log_directory: dimLogs

pandas:
  tinyset: 50000
  bigset: 500000
  parallelism: True

drivers:
  mssql: ODBC Driver 17 for SQL Server
  mysql: native

agent:
  lowdelay: 59
  highdelay: 599
  defer: False
  kill: False

smtp:
  server: 172.16.3.129
  from: EAE Data Integration <statzen@eae.inspireme.com>
  enable: false

salesforce:
  token: https://cs70.salesforce.com/services/oauth2/token
  token_ctype: application/x-www-form-urlencoded
  data_ctype: application/json
  cid: 3MVG9PE4xB9wtoY8w4VZoDIfOOua2XA_iJw9cGi270bVwJAJ6S4iZ5mcpffviN.GJ_Fx0.UF_eimRFRVmRxeL
  pwd: Passion@3owcF8Vw8VpqodZY7v9boU3Ph
  secrect: 1F35E6ED29FB35F484B562F02236479E92F16B71BE5A5B1CED787AD42EBB7D2D
  uid: divs@kcloudtechnologies.com.elearning
  dateformat: m/d/Y
  start_date: 2016-01-01
